TARGET_RECTANGLE_WIDTH = 250
TARGET_RECTANGLE_HEIGHT = 170
CENTER_X = 1280 / 2
CENTER_Y = 720 / 2
TARGET_RECTANGLE_X = CENTER_X - TARGET_RECTANGLE_WIDTH / 2
TARGET_RECTANGLE_Y = CENTER_Y - TARGET_RECTANGLE_HEIGHT / 2
CODESET = ['B', 'W', 'P', 'F', 'H', 'K', 'V', 'M', 'L', 'N', '0', 'R', '5', 'T', '7', '6', '9', 'X', 'J', '4']
