TARGET_RECTANGLE_WIDTH = 300
TARGET_RECTANGLE_HEIGHT = 200
CENTER_X = 1280/2
CENTER_Y = 720/2
TARGET_RECTANGLE_X = CENTER_X-TARGET_RECTANGLE_WIDTH/2
TARGET_RECTANGLE_Y = CENTER_Y-TARGET_RECTANGLE_HEIGHT/2